rootProject.name = "Minecraft-Plugins"

include("Sylphian-Database")
include("Sylphian-Scoreboard")
include("Sylphian-Items")
include("Sylphian-Entities")
include("Sylphian-Economy")
include("Sylphian-Skills")
include("Sylphian-Dimensions")
include("Sylphian-Crates")
include("Sylphian-Profile")
include("Sylphian-Clans")
include("Sylphian-Fishing")
include("Sylphian-Cooking")
include("Sylphian-Verify-Velocity")
include("Sylphian-Verify-Paper")
