name: Sylphian-Verify-Paper
version: '${version}'
main: net.sylphian.verify.paper.VerifyPaper
api-version: '26.1.2'
authors:
  - QuackieMackie
description: Handles player verification. Standalone mode calls the API directly. Proxy mode receives identity from Sylphian-Verify-Velocity.
dependencies:
  server:
    Sylphian-Database:
      load: BEFORE
      required: false
    Sylphian-Profile:
      load: BEFORE
      required: false
